const buttonHome = document.querySelector('.button-home')
const buttonBookmarks = document.querySelector('.button-bookmarks')
const buttonCreate = document.querySelector('.button-create')
const buttonSettings = document.querySelector('.button-settings')

const homePage = document.querySelector('.page-home')
const createPage = document.querySelector('.page-create')
const bookmarksPage = document.querySelector('.page-bookmarks')
const profilePage = document.querySelector('.page-settings')

buttonHome.addEventListener('click', () => {
  homePage.classList.remove('hidden')
  createPage.classList.add('hidden')
  bookmarksPage.classList.add('hidden')
  profilePage.classList.add('hidden')
  buttonHome.classList.add('active')
  buttonCreate.classList.remove('active')
  buttonBookmarks.classList.remove('active')
  buttonProfile.classList.remove('active')
})

buttonBookmarks.addEventListener('click', () => {
  homePage.classList.add('hidden')
  createPage.classList.add('hidden')
  bookmarksPage.classList.remove('hidden')
  profilePage.classList.add('hidden')
  buttonHome.classList.remove('active')
  buttonCreate.classList.remove('active')
  buttonBookmarks.classList.add('active')
  buttonProfile.classList.remove('active')
})

buttonCreate.addEventListener('click', () => {
  homePage.classList.add('hidden')
  createPage.classList.remove('hidden')
  bookmarksPage.classList.add('hidden')
  profilePage.classList.add('hidden')
  buttonHome.classList.remove('active')
  buttonCreate.classList.add('active')
  buttonBookmarks.classList.remove('active')
  buttonProfile.classList.remove('active')
})

buttonProfile.addEventListener('click', () => {
  homePage.classList.add('hidden')
  createPage.classList.add('hidden')
  bookmarksPage.classList.add('hidden')
  profilePage.classList.remove('hidden')
  buttonHome.classList.remove('active')
  buttonCreate.classList.remove('active')
  buttonBookmarks.classList.remove('active')
  buttonProfile.classList.add('active')
})